### ISSUE TITLE
Wine's usr dir

### ISSUE THREAD

**Issue by Pollito001** [RazZziel/PortableLinuxGames#12]
In the example of make wine portable apps what do you mean by path to wine's usr ?

**Comment by probonopd** [comment]
`~/path/to/wine-1.5.26-i486-1sg/usr/`

**Comment by Cosmologist** [comment]
I don't understand too - the path "~ /path/to/wine-1.5.26-i486-1sg/usr/" does not exist. I can create a folder, but what should I put in it? Extract wine*.deb/CONTENTS/usr? Can I use the path to an already installed wine like '/usr/lib/wine/'?

**Comment by Cosmologist** [comment]
Guys, do not waste time - the instructions for wine applications do not reveal important nuances, without which it will not be possible to build the app. I was able to pack the Wine application and run it, but this project is very crude - a lot of dirty hacks, unstable work and lack of proper documentation. The easiest way is to try to find a normal build tool, or do it manually, or maybe say no to appimage )))

**Comment by Cosmologist** [comment]
If someone wants to try it all the same - write to me - I will tell you how I did it - if I don’t forget by this time )))

**Comment by RazZziel** [comment]
Thanks for bringing this hole in the documentation to my attention @Cosmologist, and excuse me for the 4 year late reply.

_"Wine's usr"_ means the `/usr` path inside a Wine binary package.

You can download a Wine binary package for instance from Slackware's or Debian's packages (listed in https://wiki.winehq.org/Download):

```
raziel@Bebop ~ $ wget --content-disposition https://sourceforge.net/projects/wine/files/Slackware%20Packages/5.22/x86_64/wine-5.22-x86_64-1sg.txz/download -O wine-5.22-x86_64-1sg.txz
(...)

raziel@Bebop ~ $ mkdir wine-5.22-x86_64-1sg

raziel@Bebop ~ $ tar -xf wine-5.22-x86_64-1sg.txz -C wine-5.22-x86_64-1sg
```

Then you can find there the `usr/` directory I'm talking about in the Wiki:

```
raziel@Bebop ~ $ ls wine-5.22-x86_64-1sg/usr/
bin  doc  include  lib  lib64  man  share
```

I've just modified [Portable Wine installation](https://github.com/RazZziel/PortableLinuxGames/wiki/Creating-appimages-from-Windows-applications#portable-wine-installation). I think it's more understable now. Please let me know if you think there's still any missing piece of information in that or any other wiki.
